version: "3.9"

services:

  rest:
    build: ./servidor/rest
    ports:
      - "5000:5000"
    volumes:
      - ./servidor/dados/produtos.json:/app/dados/produtos.json

  graphql:
    build: ./servidor/graphql
    ports:
      - "5001:5001"
    volumes:
      - ./servidor/dados/produtos.json:/app/dados/produtos.json

  soap:
    build: ./servidor/soap
    ports:
      - "8000:8000"
    volumes:
      - ./servidor/soap/produtos.xml:/app/produtos.xml

  grpc:
    build: ./servidor/grpc
    ports:
      - "50051:50051"
    volumes:
      - ./servidor/dados/produtos.json:/app/dados/produtos.json
