# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: produtos.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'produtos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprodutos.proto\x12\x08\x63\x61talogo\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x01\n\x07Produto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05marca\x18\x03 \x01(\t\x12\r\n\x05preco\x18\x04 \x01(\x02\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x0c\n\x04tela\x18\x06 \x01(\t\x12\x0f\n\x07\x62\x61teria\x18\x07 \x01(\t\x12\x15\n\rarmazenamento\x18\x08 \x01(\t\"\x17\n\tProdutoId\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\x0fProdutoResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"4\n\rListaProdutos\x12#\n\x08produtos\x18\x01 \x03(\x0b\x32\x11.catalogo.Produto2\x9c\x02\n\x0eProdutoService\x12\x41\n\x0eListarProdutos\x12\x16.google.protobuf.Empty\x1a\x17.catalogo.ListaProdutos\x12@\n\x10\x41\x64icionarProduto\x12\x11.catalogo.Produto\x1a\x19.catalogo.ProdutoResponse\x12@\n\x0eRemoverProduto\x12\x13.catalogo.ProdutoId\x1a\x19.catalogo.ProdutoResponse\x12\x43\n\x14ListarProdutosStream\x12\x16.google.protobuf.Empty\x1a\x11.catalogo.Produto0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'produtos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUTO']._serialized_start=58
  _globals['_PRODUTO']._serialized_end=192
  _globals['_PRODUTOID']._serialized_start=194
  _globals['_PRODUTOID']._serialized_end=217
  _globals['_PRODUTORESPONSE']._serialized_start=219
  _globals['_PRODUTORESPONSE']._serialized_end=271
  _globals['_LISTAPRODUTOS']._serialized_start=273
  _globals['_LISTAPRODUTOS']._serialized_end=325
  _globals['_PRODUTOSERVICE']._serialized_start=328
  _globals['_PRODUTOSERVICE']._serialized_end=612
# @@protoc_insertion_point(module_scope)
